"""empty message

Revision ID: 127fdd34e3c1
Revises: eb3a77138afd
Create Date: 2023-11-06 01:14:48.815278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127fdd34e3c1'
down_revision = 'eb3a77138afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletterfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletterfiles')
    # ### end Alembic commands ###
