"""empty message

Revision ID: 18b06450e7cc
Revises: 127fdd34e3c1
Create Date: 2023-11-06 01:24:03.170422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b06450e7cc'
down_revision = '127fdd34e3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletterfiles', schema=None) as batch_op:
        batch_op.drop_constraint('newsletterfiles_newsletter_id_fkey', type_='foreignkey')
        batch_op.drop_column('newsletter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletterfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('newsletterfiles_newsletter_id_fkey', 'newsletter', ['newsletter_id'], ['id'])

    # ### end Alembic commands ###
