"""empty message

Revision ID: 3568888873d8
Revises: b521ddbcef95
Create Date: 2023-10-22 21:05:33.097773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3568888873d8'
down_revision = 'b521ddbcef95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
