"""empty message

Revision ID: 59a6ff98d5cd
Revises: 883ec98bdab8
Create Date: 2023-11-08 23:53:25.312544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a6ff98d5cd'
down_revision = '883ec98bdab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('profile_profile_name_key', type_='unique')
        batch_op.drop_constraint('profile_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')
        batch_op.drop_column('profile_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_profile_id_fkey', 'users', ['profile_id'], ['id'])
        batch_op.create_unique_constraint('profile_profile_name_key', ['profile_name'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
