"""empty message

Revision ID: eb3a77138afd
Revises: 516a3aa8bafa
Create Date: 2023-11-03 19:32:56.663589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3a77138afd'
down_revision = '516a3aa8bafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
